/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_2;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        System.out.println("Inserte los Cº que quiere convertir:");
        double c = scan.nextDouble();
        double f = 1.8*c+32;
        double k = c+273.15;
        System.out.println( c+"Cº es equivalente a "+k+" Kelvin o "+f+" Fahrenheit");
    }
}
