/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_3;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        System.out.println("Cantidad de billetes de 100:");
        double c = scan.nextDouble();
        System.out.println("Cantidad de billetes de 20:");
        double v = scan.nextDouble();
        System.out.println("Cantidad de billetes de 5:");
        double ci = scan.nextDouble();
        System.out.println("Cantidad de monedas de 1:");
        double ut = scan.nextDouble();
        double ct = c *100;
        double vt = v * 20;
        double cit = ci * 5;
        System.out.println("La cantidad total de dinero es: "+(ut+ct+vt+cit)+"€.");
    }
}
