/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin6_1;

public class App {

    public static void main(String[] args) {
        Coche coche1 = new Coche();
        coche1.acelerar(360);
        coche1.frenar(186);
        System.out.println(coche1.getVelocidade());
    }
}
