/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_4;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        System.out.println("Inserte la cantidad de dinero a dividir:");
        double d = scan.nextDouble();
        int c = (int)(d/100);
        int v = (int)(d%100)/20;
        int ci = (int)(d%100%20)/5;
        int u = (int)(d%100%20%5);
        System.out.println(d+"€ son equivalentes a "+ c+" billete(s) de 100,"+ v +" billete(s) de 20,"+ci+" billete(s) de 5 y "+u+" moneda(s) de 1.");
    }
}