/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin6_3;

public class App {

    public static void main(String[] args) {
        circulo circ1 = new circulo(7);
        System.out.println(circ1.calcularArea() + "\n" + circ1.calcularLonxitude());
    }
}
